// CONTROLLER — generatePropertyPdf(propertyId) → get property + images, build PDF, return bytes
import type { SupabaseClient } from "@supabase/supabase-js";
import { jsPDF } from "jspdf";
import * as propertyModel from "@/models/property.model";
import * as propertyImageModel from "@/models/property_image.model";

export async function generatePropertyPdf(
  supabase: SupabaseClient,
  propertyId: string
): Promise<{ data: Uint8Array | null; error: string | null }> {
  const { data: property, error: propError } = await propertyModel.getById(
    supabase,
    propertyId
  );
  if (propError || !property) {
    return {
      data: null,
      error: (propError as Error)?.message ?? "Property not found",
    };
  }

  const { data: images } = await propertyImageModel.listByPropertyId(
    supabase,
    propertyId
  );

  const doc = new jsPDF();
  const lineHeight = 7;
  let y = 20;

  doc.setFontSize(18);
  doc.text(property.title, 20, y);
  y += lineHeight * 2;

  doc.setFontSize(11);
  doc.text(`Type: ${property.type}  |  Category: ${property.category}`, 20, y);
  y += lineHeight;
  doc.text(`Price: BDT ${Number(property.price).toLocaleString()}`, 20, y);
  y += lineHeight;
  doc.text(`Address: ${property.address}`, 20, y);
  y += lineHeight;
  doc.text(
    `Area: ${property.area_sqft} sq ft  |  Bedrooms: ${property.bedrooms}  |  Bathrooms: ${property.bathrooms}`,
    20,
    y
  );
  y += lineHeight * 1.5;

  doc.text("Description:", 20, y);
  y += lineHeight;
  const descLines = doc.splitTextToSize(property.description || "—", 170);
  doc.text(descLines, 20, y);
  y += descLines.length * lineHeight + lineHeight;

  if (images.length > 0) {
    doc.text("Images:", 20, y);
    y += lineHeight;
    images.slice(0, 5).forEach((img, i) => {
      doc.setFontSize(9);
      doc.text(`${i + 1}. ${img.url}`, 20, y);
      y += lineHeight;
    });
  }

  doc.text(
    `Generated by VaraNow — ${new Date().toISOString().slice(0, 10)}`,
    20,
    doc.internal.pageSize.height - 10
  );

  const bytes = doc.output("arraybuffer");
  return { data: new Uint8Array(bytes), error: null };
}
